import type { Metadata } from "next";
import "./globals.css";
import { Outfit } from "next/font/google";
import SideNavigation from "./_components/SideNavigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} bg-very-dark-blue antialiased flex gap-[3.6rem] min-h-screen min-w-full`}
      >
        <SideNavigation />

        <div className=" border-blue-500 w-full mt-8">{children}</div>
      </body>
    </html>
  );
}
