import type { Metadata } from "next";
import "./globals.css";
import { Outfit } from "next/font/google";
import SideNavigation from "./_components/SideNavigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} bg-very-dark-blue antialiased`}>
        <div className="flex min-h-screen gap-[3.2rem] px-[3.2rem] py-[3.2rem]">
          <div className="fixed">
            <SideNavigation />
          </div>

          <main className="ml-[11.2rem] h-[calc(100vh-6.4rem)] flex-1 overflow-y-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
