import type { Metadata } from "next";
import "./globals.css";
import { Outfit } from "next/font/google";
import { BookmarkedMoviesProvider } from "./_context/BookmarkedMoviesContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} bg-very-dark-blue antialiased`}>
        <BookmarkedMoviesProvider>{children}</BookmarkedMoviesProvider>
      </body>
    </html>
  );
}
